# Generated by Django 4.1 on 2023-02-19 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Категория аты')),
                ('slug', models.SlugField(verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категориялар',
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Есімі')),
                ('last_name', models.CharField(max_length=150, verbose_name='Тегі')),
                ('phone', models.CharField(max_length=16, verbose_name='Телефон номері')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Қатысушы',
                'verbose_name_plural': 'Қатысушылар',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Есімі')),
                ('phone', models.CharField(max_length=16, verbose_name='Телефон номері')),
                ('message', models.TextField(verbose_name='Хабарлама')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Хабарлама келген уақыт')),
            ],
            options={
                'verbose_name': 'Сұрақ',
                'verbose_name_plural': 'Сұрақтар',
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/', verbose_name='Файл')),
                ('score', models.IntegerField(verbose_name='Ұпай')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.participant', verbose_name='Қатысушы')),
            ],
            options={
                'verbose_name': 'Нәтиже',
                'verbose_name_plural': 'Нәтижелер',
            },
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Байқау аты')),
                ('image', models.ImageField(upload_to='contest_images/', verbose_name='Банер')),
                ('description', models.TextField(verbose_name='Байқау сипаттамасы')),
                ('slug', models.SlugField(verbose_name='Слаг(адресс)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Жарияланған күні')),
                ('date', models.DateTimeField(verbose_name='Байқау болатын уақыт')),
                ('status', models.BooleanField(default=True, verbose_name='Белсенді/Белсенді емес')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Байқау',
                'verbose_name_plural': 'Байқаулар',
                'ordering': ['-created'],
            },
        ),
    ]
