# Generated by Django 4.1 on 2023-02-22 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_participant_options_alter_participant_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.contest', verbose_name='Байқау')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.participant', verbose_name='Қатысушы')),
            ],
            options={
                'verbose_name': 'Дауыс беру',
                'verbose_name_plural': 'Дауыс берулер',
            },
        ),
    ]
