# Generated by Django 4.1 on 2023-02-22 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_alter_participant_user_alter_vote_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Тіркелуші'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.participant', verbose_name='Қатысушы'),
        ),
    ]
