# Generated by Django 4.1 on 2023-04-11 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_vote_user_alter_vote_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='open_close',
            field=models.BooleanField(default=False, verbose_name='Жабық байқау ма?'),
        ),
        migrations.AddField(
            model_name='participant',
            name='status_jury',
            field=models.BooleanField(default=False, verbose_name='Әділ-қазы статусы'),
        ),
    ]
