# Generated by Django 4.1 on 2023-04-11 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_contest_open_close_participant_status_jury'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='status_jury',
        ),
        migrations.CreateModel(
            name='Jury',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_jury', models.BooleanField(default=False, verbose_name='Әділ-қазы статусы')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.contest', verbose_name='Байқау')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Әділ қазы',
                'verbose_name_plural': 'Әділ қазылар',
            },
        ),
    ]
